#!/usr/bin/env bash

# Go fast on AC power.  Similar to default Ubuntu settings
if on_ac_power; then
  # Set the drive to mostly stay awake.  Some may want to change -B 254
  # to -B 255 to avoid accumulating Load_Cycle_Counts
  hdparm -B 254 -S 240 -M 254 /dev/sda

  # Remount ext3 filesystems so the journal commit only happens every 60
  # seconds.  By default this is 5 but, I prefer to reduce the disk
  # activity a bit.
  #mount -o remount,commit=60 /
  #mount -o remount,commit=60 /home

  # Turn off the laptop mode disk optimization
  echo 0 > /proc/sys/vm/laptop_mode

  # Set kernel dirty page value back to default
  echo 10 > /proc/sys/vm/dirty_ratio
  echo 5 > /proc/sys/vm/dirty_background_ratio

  # Only wakeup every 60 seconds to see if we need to write dirty pages
  # By default this is every 5 seconds but, I prefer 60 to reduce disk
  # activity.
  echo 6000 > /proc/sys/vm/dirty_writeback_centisecs

  # Turn off sound card power savings
  echo 0 > /sys/module/snd_hda_intel/parameters/power_save
  
  # Set the SATA to max performance
  echo max_performance > /sys/class/scsi_host/host0/link_power_management_policy
  echo max_performance > /sys/class/scsi_host/host1/link_power_management_policy

  # Make sure ondemand governor is set
  echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 

  # Enable the webcam driver
#  modprobe uvcvideo

  #restart bluetooth #you can also decide to use RFKILL here. 
  sudo /usr/sbin/hciconfig hci0 up

  # Start optional  services
#  sudo /etc/init.d/cron start
  sudo /etc/init.d/bluetooth start
  sudo /etc/init.d/preload start

  #reset brightness of screen and keyboard
  #sudo nvclock -S 85
  sudo echo 50 | sudo tee -a /sys/class/leds/smc::kbd_backlight/brightness

  #Enable eth0
  sudo ifconfig eth0 up

  #reset clock nvidia card (requires coolbits=1)
  #sudo nvidia-settings -a GPU2DClockFreqs=100,0
  #sudo nvidia-settings -a GPU3DClockFreqs=450,0

  #tuned
  tuned-adm profile laptop-ac-powersave
  

else # Save power

  # Set the disks to aggressively save power and use the lowest acoustic
  # level.  Some might find these settings too aggressive.  If so, change 
  # "-S 4" to something larger like -S 24 (two minutes) and -B 128 to -B 254.
  hdparm -B 128 -S 4 -M 128 /dev/sda
  
  # Change the ext3 commit times to 10 minutes.  This reduces diskhcd
  # activity
  #mount -o remount,commit=600 /

  # Set laptop disk write mode
  echo 5 > /proc/sys/vm/laptop_mode

  # Manually set the iwl3945 driver to power savings.
  #echo 5 > /sys/bus/pci/drivers/iwl????/0000\:??\:00.0/power_level  

  # Reduce disk activity by waiting up to 10 minutes before doing writes
  echo 90 > /proc/sys/vm/dirty_ratio
  echo 1 > /proc/sys/vm/dirty_background_ratio
  echo 60000 > /proc/sys/vm/dirty_writeback_centisecs

  # Set sound card power savings
  echo 10 > /sys/module/snd_hda_intel/parameters/power_save

  # Set SATA to minimum power
  echo min_power > /sys/class/scsi_host/host0/link_power_management_policy
  echo min_power > /sys/class/scsi_host/host1/link_power_management_policy

  # Make sure ondemand governor is set
  echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
  
  # Remove the webcam driver
#  modprobe -r uvcvideo

  #Disable eth0
  sudo ifconfig eth0 down

  # Stop unneccessary  services
#  sudo /etc/init.d/cron stop
  sudo /etc/init.d/bluetooth stop
  sudo /etc/init.d/preload stop

  #poweroff bluetooth
  sudo /usr/sbin/hciconfig hci0 down

  #dim screen and keyboard brightness to minimum
  #sudo nvclock -S 15
  sudo echo 0 | sudo tee -a /sys/class/leds/smc::kbd_backlight/brightness

  #downclock nvidia card (requires coolbits=1)
  #sudo nvidia-settings -a GPU2DClockFreqs=25,0
  #sudo nvidia-settings -a GPU3DClockFreqs=125,0
  
  #tuned
  tuned-adm profile laptop-battery-powersave
fi 
